# Generated by Django 4.0.5 on 2022-07-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.services_table')),
            ],
        ),
    ]
