# Generated by Django 4.0.5 on 2022-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_offers_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers_table',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
