# Generated by Django 4.0.5 on 2022-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company_table_offers_table_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers_table',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
