# Generated by Django 4.0.5 on 2022-07-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_company_table_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('tel', models.IntegerField()),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.offers_table')),
            ],
        ),
    ]
