# Generated by Django 4.0.5 on 2022-07-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_table',
            name='user',
        ),
    ]
