# Generated by Django 4.0.5 on 2022-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_client', '0002_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
